version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret_docker
      - POSTGRES_DB=apisolid
